# Generated by Django 3.0.8 on 2020-07-24 19:07

from django.db import migrations, models
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200721_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerId',
        ),
        migrations.AddField(
            model_name='customer',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=''),
        ),
    ]
